name: Update Sitemap

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    steps:
      # Checkout the main branch to get the latest code
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Set your required Node.js version

      # Install dependencies using npm
      - name: Install dependencies
        run: npm install

      # Generate the sitemap using your custom script
      - name: Generate Sitemap
        run: npm run sitemap
        env:
          SITE_URL: "https://www.terminaltales.com/"

      # Debugging step: List files to verify the sitemap location
      - name: List files in project directory
        run: ls -R
        # If you expect sitemap in a specific subdirectory, adjust the path, e.g., `ls -R build/`

      # Commit changes to the main branch before switching to gh-pages
      - name: Commit Changes on Main
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add build/sitemap.xml package-lock.json public/sitemap.xml || echo "Nothing to add"
          git commit -m "Update sitemap files before switching branches" || echo "No changes to commit"

      # Switch to gh-pages branch to deploy the sitemap
      - name: Switch to gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      # Copy the generated sitemap to the gh-pages branch
      - name: Copy Sitemap to gh-pages
        run: |
          # Adjust the path if the sitemap is found in a different location during the listing step
          cp build/sitemap.xml sitemap.xml

      # Commit and push the sitemap changes if there are any
      - name: Commit and Push Sitemap Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add sitemap.xml
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update sitemap"
            git push
          fi
